# Generated by Django 4.1.4 on 2022-12-28 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('user', models.CharField(max_length=50)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriteproducts', to='product.product')),
            ],
        ),
    ]
